xp:
  base: 100.0       # (für PlayerLevel.configure)
  multiplier: 1.15
  max-level: 100

  # Anzeige-Optionen für "+XP"
  announce:
    chat: false           # false setzen, wenn du die Chat-Meldung ausschalten willst (z. B. wenn PlayerLevel selbst meldet)
    color: "#FFD166"      # Farbe der Chat-Meldung

  mobs:
    default: 0

    # Gruppen (werden nur genutzt, wenn der exakte Mob nicht definiert ist)
    HOSTILE: 4
    PASSIVE: 1
    NEUTRAL: 2

    # Exakte Mobs (haben Vorrang vor Gruppen)
    WITCH: 20
    ZOMBIE: 6
    SKELETON: 6
    SPIDER: 6
    CREEPER: 8
    ENDERMAN: 12

    IRON_GOLEM: 10   # <-- jetzt explizit drin
    SNOW_GOLEM: 3
    WOLF: 2

    COW: 5
    SHEEP: 5
    PIG: 5
    CHICKEN: 5


mana:
  base-max: 50.0
  per-level: 5.0
  base-regen: 1.0
  regen-per-level: 0.1


ability:
  damage_boost:
    cost: 25.0
    multiplier: 1.5
    duration-ticks: 60
    cooldown-ticks: 100


rarities:
  COMMON: "#C0C0C0"
  UNCOMMON: "#55FF55"
  RARE: "#5555FF"
  EPIC: "#AA00FF"
  LEGENDARY: "#FFAA00"
  MYTHIC: "#FF3366"

lore_colors:
  damage:      "#FF5555"
  critchance:  "#FFFF55"
  critdamage:  "#FFAA00"
  health:      "#FF5555"
  armor:       "#AAAAAA"
  range:       "#00AAAA"
  mana:        "#55FFFF"
  manaregen:   "#55FFFF"
  custom:      "#BFBFBF"
  healthregen: "#FF5555"
  attackspeed: "#FF55FF"
  speed: "#FFFFFF"
  Blau: "#5555FF"

stats_display:
  order:
    - damage
    - critchance
    - critdamage
    - attackspeed
    - range
    - health
    - healthregen
    - armor
    - mana
    - manaregen
    - speed

  colors:
    damage:      "#FF5555"
    critchance:  "#FFFF55"
    critdamage:  "#FFAA00"
    attackspeed: "#FF55FF"
    range:       "#00AAAA"
    health:      "#FF5555"
    armor:       "#AAAAAA"
    mana:        "#55FFFF"
    manaregen:   "#55FFFF"
    healthregen: "#FF5555"
    speed:       "#FFFFFF"

  labels:
    header_stats: "=== Stats ==="
    damage: "Damage"
    critchance: "Crit Chance"
    critdamage: "Crit Damage"
    attackspeed: "Attack Speed"
    range: "Reach"
    health: "Health"
    armor: "Armor"
    mana: "Mana"
    manaregen: "Mana Regen"
    healthregen: "Health Regen"
    speed: "Speed"
    header_level: "=== Level & XP ==="
    level: "Level"
    xp: "XP"
    skillpoints: "Skill Points"

combat:
  knockback:
    base: 0.40
    y: 0.35


loot:
  tables:
    dungeon_basic:
      rolls: 3
      entries:
        - template: ayri_ingot
          min: 2
          max: 3
          weight: 47
        - template: ayri_powder
          min: 2
          max: 3
          weight: 47
        - template: ayri_key
          min: 1
          max: 1
          weight: 5
        - template: ayri_axe
          min: 1
          max: 1
          weight: 1



    zombie_easy:
      rolls: 1           # wie oft gelootet wird (2x aus der Tabelle ziehen)
      entries:
        - template: starter_sword   # Name aus /itemtpl save
          weight: 5                 # Gewicht (je höher, desto wahrscheinlicher)
          min: 1                    # min. Anzahl
          max: 1                    # max. Anzahl
        - template: basic_potion
          weight: 20
          min: 1
          max: 3
        - template: coins_small
          weight: 40
          min: 5
          max: 15

    zombie_warrior:
      rolls: 2
      entries:
        - template: ayri1
          weight: 10
          min: 1
          max: 1
        - template: ayri2
          weight: 30
          min: 10
          max: 25

    skeleton_archer:
      rolls: 3
      entries:
        - template: warrior_sword_t2
          weight: 10
          min: 1
          max: 1
        - template: warrior_armor_t2
          weight: 5
          min: 1
          max: 1
        - template: coins_big
          weight: 40
          min: 20
          max: 50

  mobs:
    ZOMBIE: zombie_easy
    HUSK: zombie_easy
    DROWNED: zombie_easy

  custom_mobs:
    zombie_warrior: zombie_warrior
    skeleton_archer: skeleton_archer