xp:
  max-level: 100
  base: 100.0
  multiplier: 1.15

mana:
  base-max: 50.0
  per-level: 5.0
  base-regen: 1.0
  regen-per-level: 0.1


ability:
  damage_boost:
    cost: 25.0
    multiplier: 1.5
    duration-ticks: 60
    cooldown-ticks: 100


rarities:
  COMMON: "#C0C0C0"
  UNCOMMON: "#55FF55"
  RARE: "#5555FF"
  EPIC: "#AA00FF"
  LEGENDARY: "#FFAA00"
  MYTHIC: "#FF3366"

lore_colors:
  damage:      "#FF5555"
  critchance:  "#55FFFF"
  critdamage:  "#FFD700"
  health:      "#FF5555"
  armor:       "#AAAAAA"
  range:       "#55FF55"
  mana:        "#00AAFF"
  manaregen:   "#00AAFF"
  custom:      "#BFBFBF"
  healthregen: "#FF7777"
  attackspeed: "#FF7777"
