xp:
  base: 100.0       # (für PlayerLevel.configure)
  multiplier: 1.15
  max-level: 100

  # Anzeige-Optionen für "+XP"
  announce:
    chat: false           # false setzen, wenn du die Chat-Meldung ausschalten willst (z. B. wenn PlayerLevel selbst meldet)
    color: "#FFD166"      # Farbe der Chat-Meldung

  mobs:
    default: 0

    # Gruppen (werden nur genutzt, wenn der exakte Mob nicht definiert ist)
    HOSTILE: 4
    PASSIVE: 1
    NEUTRAL: 2

    # Exakte Mobs (haben Vorrang vor Gruppen)
    WITCH: 20
    ZOMBIE: 6
    SKELETON: 6
    SPIDER: 6
    CREEPER: 8
    ENDERMAN: 12

    IRON_GOLEM: 10   # <-- jetzt explizit drin
    SNOW_GOLEM: 3
    WOLF: 2

    COW: 5
    SHEEP: 5
    PIG: 5
    CHICKEN: 5


mana:
  base-max: 50.0
  per-level: 5.0
  base-regen: 1.0
  regen-per-level: 0.1


ability:
  damage_boost:
    cost: 25.0
    multiplier: 1.5
    duration-ticks: 60
    cooldown-ticks: 100


rarities:
  COMMON: "#C0C0C0"
  UNCOMMON: "#55FF55"
  RARE: "#5555FF"
  EPIC: "#AA00FF"
  LEGENDARY: "#FFAA00"
  MYTHIC: "#FF3366"

lore_colors:
  damage:      "#FF5555"
  critchance:  "#55FFFF"
  critdamage:  "#FFD700"
  health:      "#FF5555"
  armor:       "#AAAAAA"
  range:       "#55FF55"
  mana:        "#00AAFF"
  manaregen:   "#00AAFF"
  custom:      "#BFBFBF"
  healthregen: "#FF7777"
  attackspeed: "#FF7777"
  speed: "FFFFFF"

stats_display:
  order:
    - damage
    - critchance
    - critdamage
    - attackspeed
    - range
    - health
    - armor
    - mana
    - manaregen
    - healthregen
    - speed

  colors:
    damage:      "#FF5555"
    critchance:  "#55FFFF"
    critdamage:  "#FFD166"
    attackspeed: "#FFD166"
    range:       "#55FF55"
    health:      "#FF4444"
    armor:       "#AAAAAA"
    mana:        "#55AAFF"
    manaregen:   "#55AAFF"
    healthregen: "#FF77AA"
    speed:       "#FFFFFF"

  labels:
    header_stats: "=== Stats ==="
    damage: "Damage"
    critchance: "Crit Chance"
    critdamage: "Crit Damage"
    attackspeed: "Attack Speed"
    range: "Range"
    health: "Health"
    armor: "Armor"
    mana: "Mana"
    manaregen: "Mana Regen"
    healthregen: "Health Regen"
    speed: "Speed"
    header_level: "=== Level & XP ==="
    level: "Level"
    xp: "XP"
    skillpoints: "Skill Points"

combat:
  knockback:
    base: 0.40
    y: 0.35